server:
  port: 8082

spring:
  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    baseUrl: http://localhost:8084

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
