global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-ui-actuator'
    metrics_path: "actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: [ '10.0.0.83:8101' ]

  - job_name: 'user-store-actuator'
    metrics_path: "actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: [ '10.0.0.83:8100' ]

  - job_name: 'user-i18n-actuator'
    metrics_path: "actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: [ '10.0.0.83:8102' ]

