server:
  port: 8100

spring:
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    username: sa
    password: abc
    url: jdbc:h2:G:/techbow/techbow_services/mapped-volumes/h2/user-store;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
    path: /h2/console

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    baseUrl: http://localhost:8084


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

