spring:
  application:
    name: user-i18n-service

  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: "ALWAYS"

  config:
    import: optional:configserver:http://localhost:8081/